version: "3.9"
services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  php-cli:
    build: ./php-cli
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:alpine
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"

